# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
      time: "20:00"
    assignees:
      - xosnrdev
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      dev-deps:
        dependency-type: development
        update-types:
          - patch
          - minor
      deps:
        dependency-type: production
        update-types:
          - patch
          - minor

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "20:02"
    assignees:
      - xosnrdev
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      ci-deps:
        update-types:
          - patch
          - minor