name: Main Build

on:
  release:
    types: [released]
  workflow_dispatch:

env:
  DOCKER_IMAGE: toolkithub/rce-engine:1.2.4

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Nix and Build Docker Image
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05
          github_access_token: ${{ secrets.GH_TOKEN }}

      - name: Build and Load Docker Image
        run: |
          nix-build -o result/rce-engine docker.nix
          docker load -i result/rce-engine

      - name: Push to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Image
        run: docker push ${{ env.DOCKER_IMAGE }}
