name: 🚀 release

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  APP_NAME: rce-engine
  ARCHIVE_NAME: rce-engine_linux-x64.tar.gz
  CONTENT_TYPE: application/gzip
  GITHUB_REF_NAME: ${{ github.ref_name }}
  GITHUB_REPOSITORY: ${{ github.repository }}

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Build and Package Binary
        run: |
          nix build
          tar -czf "${ARCHIVE_NAME}" -C target/release "${APP_NAME}"
          echo "UPLOAD_URL=$(jq -r '.release.upload_url' "$GITHUB_EVENT_PATH" | sed -e "s/{?name,label}$/?name=${ARCHIVE_NAME}/")" >> $GITHUB_ENV

      - name: Upload Release Asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ${{ env.ARCHIVE_NAME }}
          asset_name: ${{ env.ARCHIVE_NAME }}
          asset_content_type: ${{ env.CONTENT_TYPE }}
          github_token: ${{ secrets.GH_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Image
        run: nix build .#docker

      - name: Load Docker Image
        run: |
          docker load -i result

      - name: Push Docker Image
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          docker push $GITHUB_REPOSITORY:$VERSION
