name: Main Release

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  APP_NAME: rce-engine
  DOCKER_IMAGE: toolkithub/rce-engine:edge
  ARCHIVE_NAME: rce-engine_linux-x64.tar.gz

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build and Package Binary
        run: |
          cargo build --release
          tar -czf "${ARCHIVE_NAME}" -C target/release "${APP_NAME}"
          echo "UPLOAD_URL=$(jq -r '.release.upload_url' "$GITHUB_EVENT_PATH" | sed -e "s/{?name,label}$/?name=${ARCHIVE_NAME}/")" >> $GITHUB_ENV

      - name: Upload Release Asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ${{ env.ARCHIVE_NAME }}
          asset_name: ${{ env.ARCHIVE_NAME }}
          asset_content_type: application/gzip
          github_token: ${{ secrets.GH_TOKEN }}

      - name: Setup Nix and Build Docker Image
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05
          github_access_token: ${{ secrets.GH_TOKEN }}

      - name: Build and Load Docker Image
        run: |
          nix-build -o result/rce-engine docker.nix
          docker load -i result/rce-engine

      - name: Push to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Image
        run: docker push ${{ env.DOCKER_IMAGE }}
