name: Build and upload release

on:
  release:
    types: [created]

  workflow_dispatch:

env:
  APP_NAME: rce-engine
  ARCHIVE_NAME: rce-engine_linux-x64.tar.gz

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install latest rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.79.0

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.release.tag_name || github.event.inputs.release_tag }}

      - name: Set upload URL
        run: |
          echo "UPLOAD_URL=${{ steps.get_release.outputs.upload_url }}" >> $GITHUB_ENV
          echo "Upload URL: ${{ steps.get_release.outputs.upload_url }}"

      - name: Build release asset
        run: |
          cargo build --release
          tar -czf $ARCHIVE_NAME -C target/release $APP_NAME

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ${{ env.ARCHIVE_NAME }}
          asset_name: ${{ env.ARCHIVE_NAME }}
          asset_content_type: application/gzip
