name: Systems Nightly

on:
  push:
    branches:
      - main
      - development

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05
          github_access_token: ${{ secrets.GH_TOKEN }}

      - name: Pull rce-images-python
        run: |
          docker pull ghcr.io/toolkithub/rce-images-python:edge

      - name: Setup docker environment
        run: |
          chmod +x ./run.sh
          ./run.sh &

      - name: Wait for server to start
        run: |
          sleep 10

      - name: Run test
        run: |
          output=$(curl -s -X POST \
            -H "X-Access-Token: ${{ secrets.RCE_ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"image": "ghcr.io/toolkithub/rce-images-python:edge", "payload": {"language": "python", "files": [{"name": "main.py", "content": "print(42)"}]}}' \
            http://localhost:50051/run
          )

          echo "Output: ${output}"

          if [[ "${output}" == *"42"* ]]; then
            echo "Test passed."
          else
            echo "Test failed."
            exit 1
          fi

      - name: Shutdown server gracefully
        run: |
          pid=$(lsof -t -i:50051)
          if [[ -n "${pid}" ]]; then
            kill -TERM "${pid}"
            echo "Server shutdown gracefully."
          else
            echo "No server running on port 50051."
          fi
