name: Main Test

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    env:
      PORT: 50051
      TEST_IMAGE: toolkithub/python:edge
      TEST_PAYLOAD: '{"image":"toolkithub/python:edge","payload":{"language":"python","files":[{"name":"main.py","content":"print(42)"}]}}'
      EXPECTED_OUTPUT: "42"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Test Environment
        run: |
          docker pull ${{ env.TEST_IMAGE }}
          chmod +x ./scripts/run.sh
          ./scripts/run.sh &
          sleep 60

      - name: Run Smoke Test
        run: |
          response=$(curl -s -X POST \
            -H "X-Access-Token: ${{ secrets.API_ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '${{ env.TEST_PAYLOAD }}' \
            http://localhost:${{ env.PORT }}/run)

          echo "${response}"
          [[ "${response}" == *"${{ env.EXPECTED_OUTPUT }}"* ]] || exit 1

      - name: Cleanup
        if: always()
        run: |
          if pid=$(lsof -t -i:${{ env.PORT }}); then
            kill -TERM "${pid}"
            echo "Server stopped"
          fi
